### PR TITLE
GraphQL Testing

### PR DESCRIPTION
**Pull request by ntietz**
This PR adds tests and adds some general improvements from Nicholas and Kyle.

### CODE REVIEW

**Comment by Koleok** [comment]
This looks great since we have both hacked away at it at length now :)

**Review by Koleok — APPROVED** [review]
Well i am happy as a 🐟 about this

**Comment by Koleok** [comment]
There is nothing automated set up for this yet right @ntietz? So it would be safe to go ahead and merge?

I have wanted to do that with these PRs but was not totally sure what your deployment workflow was looking like on this yet and don't want to cause any hangups.

**Comment by ntietz** [comment]
@Koleok correct, merges are in general safe.

**Pull request merged**
